name: test

on:
  push:
    branches: [dev]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
      - "pyproject.toml"
  pull_request:
    branches: [dev, main]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: ${{ matrix.python-version }} 
      
      - id: echo-python-path
        run: |
          export PYTHON_PATH=$(python -c "import sys; print(sys.executable)")
          export PYTHON_VERSION=$(python -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}.{sys.version_info.micro}')")
          echo "PYTHON_PATH=$PYTHON_PATH" >> $GITHUB_OUTPUT
          echo "PYTHON_VERSION=$PYTHON_VERSION" >> $GITHUB_OUTPUT

      - name: Install rye
        uses: phi-friday/install-rye@v1.5
        id: install-rye

      - name: Install dependencies
        run: |
          rye install uv
          rye build
          uv pip compile pyproject.toml -o requirements.txt --extra test
          export UV_PYTHON=${{ steps.echo-python-path.outputs.PYTHON_PATH }}
          uv venv
          uv pip install -r requirements.txt
          uv pip install dist/airflow_serde_polars-0.0.0-py3-none-any.whl

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest