name: test

on:
  push:
    branches: [dev]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
      - "pyproject.toml"
  pull_request:
    branches: [dev, main]
    paths:
      - "**.py"
      - ".github/workflows/check.yaml"
      - "pyproject.toml"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      
      - name: Install rye
        uses: phi-friday/install-rye@v1.5
        id: install-rye
        with:
          python_version: ${{ matrix.python-version }}
          use_uv: true

      - name: Install dependencies
        run: |
          rye install uv
          rye build
          rye lock # init venv
          export UV_PYTHON=$(rye run python -c "import sys; print(sys.executable)")
          uv pip compile pyproject.toml -o requirements.txt --extra test
          rye run python -m ensurepip
          rye run python -m pip install -r requirements.txt
          rye run python -m pip install dist/airflow_serde_polars-0.0.0-py3-none-any.whl

      - name: Test with pytest
        run: |
          source .venv/bin/activate
          pytest